README.md, packages/cloudflare/README.md
refs https://github.com/opennextjs/docs/pull/3/
=> link to OpenNext docs from readme

packages/cloudflare/src/cli/build/patches/to-investigate/inline-next-require.ts
I have no idea how this was not breaking anything 😕
=> fix wrong config import path

examples/api/package.json, packages/cloudflare/src/cli/templates/worker.ts
=> make sure that `@opennextjs/cloudflare` can be used in projects with `type` set to `module`

.github/ISSUE_TEMPLATE/config.yml
Similar to what we have at https://github.com/cloudflare/workers-sdk/issues/new/choose
=> Add link to the Open Next Discord

packages/cloudflare/package.json, pnpm-lock.yaml
=> chore: update opennext/aws

.github/workflows/checks.yml
Enables code quality + unit test checks for experimental branch PRs.
=> run code quality workflow checks on experimental branch prs

.changeset/strong-crabs-deliver.md, packages/cloudflare/package.json, pnpm-lock.yaml
=> fix: cleanup dependencies

.changeset/stupid-geese-reply.md, packages/cloudflare/src/cli/build/index.ts
=> show error for next.js versions older than v14

.changeset/violet-zebras-notice.md, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts
fixes #245 
@vicb so sorry, I did notice this mistake when I worked on the patch and did fix it, I must have not pushed that change up or something like that, sorry 🙇
=> fix broken `patchRequireReactDomServerEdge` patch

.changeset/soft-stingrays-thank.md, packages/cloudflare/package.json, pnpm-lock.yaml
fixes #252 
___
opennext-aws PR: https://github.com/opennextjs/opennextjs-aws/pull/704
=> fix top level awaits not working in middlewares by bumping the `@opennextjs/aws` package

.changeset/four-crabs-carry.md, packages/cloudflare/package.json, packages/cloudflare/src/cli/build/bundle-server.ts, pnpm-lock.yaml
`@opennextjs/aws@715` generates [meta files](https://github.com/opennextjs/opennextjs-aws/pull/715). This will help us investigate #14
=> Dump ESBuild metadata to handler.mjs.meta.json

.changeset/spicy-turkeys-share.md, packages/cloudflare/src/cli/build/bundle-server.ts
Not sure how this flew under the radar for so long!
=> fix: syntax error in the worker banner

examples/e2e/app-pages-router/package.json, examples/e2e/app-router/package.json, examples/e2e/pages-router/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Sorry @dario-piotrowicz I missed that when merging the e2e PRs
=> chore: add missing wrangler in devDependencies

.changeset/honest-mayflies-behave.md, examples/next-partial-prerendering/package.json, packages/cloudflare/package.json, pnpm-lock.yaml
fixes #309 
Pull the workaround from https://github.com/opennextjs/opennextjs-aws/pull/718
=> fix: enable PPR with `wrangler dev`

.changeset/nice-penguins-boil.md, examples/e2e/app-router/e2e/trailing.test.ts, packages/cloudflare/package.json, pnpm-lock.yaml
fixes #312
Pulll the upstream fix: https://github.com/opennextjs/opennextjs-aws/pull/722
=> fix: trailing slash redirect

packages/cloudflare/src/cli/build/bundle-server.ts
EsBuild throws id there are errors so this code is not helpful
=> refactor: remove useless code

.changeset/four-seals-return.md, examples/e2e/pages-router/next.config.ts, packages/cloudflare/package.json, packages/cloudflare/src/cli/build/utils/version.ts, pnpm-lock.yaml
rewrites to external resources hosted on Cloudflare don't currently work, this PR addresses that by bumping the aws dependency
For more context see: https://github.com/opennextjs/opennextjs-aws/pull/724
=> fix external rewrites to Cloudflare hosted resources not working

.changeset/dry-fireants-smell.md, packages/cloudflare/package.json, pnpm-lock.yaml
See https://github.com/opennextjs/opennextjs-aws/pull/733
=> fix waitUntil

.changeset/config.json
This is the same format as used at https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.109.0
(Adding link to contributors)
=> chore: update the changelog format to thank contributors

package.json, packages/cloudflare/package.json, pnpm-lock.yaml
Oopsy, targeting the correct package.json this time
=> fix changeset

.changeset/five-balloons-walk.md
Let's only use minor for breaking changes before 1.0
=> chore: use patch for features before 1.0

examples/e2e/pages-router/e2e/api.test.ts, examples/e2e/pages-router/src/pages/api/dynamic/[slug].ts, examples/e2e/pages-router/src/pages/api/dynamic/catch-all-optional/[[...slug]].ts, examples/e2e/pages-router/src/pages/api/dynamic/catch-all/[...slug].ts, examples/e2e/pages-router/src/pages/api/dynamic/precedence/index.ts, examples/e2e/pages-router/src/pages/api/hello.ts
=> sync with aws

examples/playground14/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #452 
- <kbd>&nbsp;1&nbsp;</kbd> #451 👈
=> Update Next versions to latest 14 and 15

.changeset/orange-tools-approve.md, pnpm-lock.yaml, pnpm-workspace.yaml
=> Update wrangler dependency

.changeset/blue-beds-crash.md, .changeset/cuddly-mails-happen.md, .changeset/eleven-sloths-punch.md, .changeset/happy-bananas-buy.md, .changeset/lemon-donkeys-tell.md, .changeset/light-insects-kiss.md, .changeset/silly-icons-battle.md, .changeset/twelve-lizards-prove.md, packages/cloudflare/CHANGELOG.md, packages/cloudflare/package.json
With the fix for the empty tag list this time.
=> release 1.0.0-beta.3

.changeset/two-paws-boil.md, packages/cloudflare/src/api/cloudflare-context.ts, packages/cloudflare/src/api/overrides/incremental-cache/kv-incremental-cache.ts, packages/cloudflare/src/api/overrides/incremental-cache/r2-incremental-cache.ts, packages/cloudflare/src/api/overrides/internal.ts, packages/cloudflare/src/cli/commands/populate-cache.ts
- Shares cache key function between inc caches.
- Adds prefix for KV cache keys.
fixes #556
=> feat: prefix for kv cache keys

examples/prisma/package.json
to avoid a conflict with the npm package `prisma`
=> fix prisma example package name

.changeset/empty-hotels-wish.md, pnpm-lock.yaml, pnpm-workspace.yaml
Sync with the version used by aws
=> bump ESBuild to 0.25.4

examples/next-partial-prerendering/components/pricing.tsx, examples/next-partial-prerendering/components/recommended-products.tsx, examples/next-partial-prerendering/components/reviews.tsx, examples/next-partial-prerendering/components/single-product.tsx, examples/next-partial-prerendering/lib/products.ts, examples/next-partial-prerendering/lib/reviews.ts, examples/next-partial-prerendering/package.json, examples/playground14/app/isr/[id]/dynamic/page.tsx, examples/playground14/app/isr/[id]/no-dynamic/page.tsx, examples/playground14/lib/posts.ts, examples/playground15/app/isr/[id]/dynamic/page.tsx, examples/playground15/app/isr/[id]/no-dynamic/page.tsx, examples/playground15/lib/posts.ts, pnpm-lock.yaml
fixes #368 
Playground tested via e2es.
PPR tested locally after adding usage of Next's connection API.
=> remove dependency on vercel api in tests

examples/common/apps.ts, examples/next-partial-prerendering/.gitignore, examples/next-partial-prerendering/components/reviews.tsx, examples/next-partial-prerendering/e2e/playwright.config.ts, examples/next-partial-prerendering/e2e/ppr.test.ts, examples/next-partial-prerendering/open-next.config.ts, examples/next-partial-prerendering/package.json
fixes #310
Tests based off of https://github.com/opennextjs/opennextjs-cloudflare/blob/main/examples/e2e/experimental/e2e/ppr.test.ts
=> test: e2e for next-partial-prerendering example

.changeset/nine-insects-rhyme.md, packages/cloudflare/package.json, pnpm-lock.yaml
Minor release to match `@opennextjs/aws`
=> Update @opennextjs/aws to 3.7.0

.changeset/social-bushes-laugh.md, packages/cloudflare/package.json, pnpm-lock.yaml
fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/778
=> move cloudflare from devDeps to dep since it is required at runtime

.changeset/short-knives-camp.md, packages/cloudflare/src/cli/templates/images.ts
Thanks to @sommeeeer again for the suggestion 🙏
=> fallback to the content-type header

.changeset/puny-trains-return.md, packages/cloudflare/package.json, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts, packages/cloudflare/src/cli/build/utils/ensure-cf-config.ts, pnpm-lock.yaml
Sync https://github.com/opennextjs/opennextjs-aws/pull/928
=> bump @opennextjs/aws to 3.7.1
