TODO.txt, builder/src/build/build-worker/index.ts, builder/src/build/build-worker/patches/investigated/copyTemplates.ts, builder/src/build/build-worker/patches/to-investigate/inlineEvalManifest.ts, builder/src/build/build-worker/patches/to-investigate/inlineNextRequire.ts, builder/src/build/build-worker/patches/to-investigate/patchFindDir.ts, builder/src/build/build-worker/patches/to-investigate/patchReadFile.ts, builder/src/build/build-worker/patches/to-investigate/wranglerDeps.ts, next/api/package.json, pnpm-lock.yaml
- Patch source files to remove the need for aliases
=> Remove aliases

.vscode/settings.json, packages/cloudflare/src/build/build-worker.ts, packages/cloudflare/src/build/build.ts, packages/cloudflare/src/nextjs-paths.ts
In particular, rather than mutating the original `.next` files, we always make a copy to the `.worker-next/.next` directory and then mutate those.
=> move all cloudflare adapter generated files under the `.worker-next` directory

.github/workflows/playwright.yml, examples/api/package.json, examples/api/playwright.dev.config.ts, package.json, packages/cloudflare/package.json, packages/cloudflare/src/api/get-cloudflare-context.ts, packages/cloudflare/tsup.config.ts, pnpm-lock.yaml
Followup for #31 there we introduced `getCloudflareContext` in a way that would work only in production/preview, this PR  adds support for it under `next dev` (via `getPlatformProxy`)
=> enable `getCloudflareContext` to also work with `next dev`

.github/workflows/checks.yml, .github/workflows/prettier.yml, package.json, packages/cloudflare/eslint.config.mjs, packages/cloudflare/package.json, packages/cloudflare/src/api/get-cloudflare-context.ts, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/build/build-worker.ts, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-chunk-installation-identifiers.test.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-file-content-with-updated-webpack-f-require-code.test.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-updated-webpack-chunks-file-content.test.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/index.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-next-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-find-dir.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts, packages/cloudflare/src/cli/cache-handler.ts, packages/cloudflare/src/cli/config.ts, packages/cloudflare/src/cli/index.ts, packages/cloudflare/src/cli/templates/shims/node-fs.ts, packages/cloudflare/src/cli/templates/worker.ts, packages/cloudflare/tsup.config.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> Enable eslint for cloudflare package

packages/cloudflare/README.md
=> Fix package readme commands and add all the various pm variants

packages/cloudflare/package.json, packages/cloudflare/src/cli/build/build-next-app.ts, packages/cloudflare/src/cli/build/index.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> run the `next build` command using the correct package manager

packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts, packages/cloudflare/src/cli/config.ts, pnpm-lock.yaml
Next.js saves the `node_modules/next/dist` directory for the app in either the normal standalone dir or in the
standalone root path, this depends on where the next dependency is actually saved (https://github.com/vercel/next.js/blob/39e06c75/packages/next/src/build/webpack-config.ts#L103-L104) and can depend on the package manager used, if it is using workspaces, etc...
Currently we're always using the normal standalone dir but this is incorrect and causes the package not to work in certain projects, this PR fixes such issue.
___
> [!NOTE]
> I would have liked to add an e2e test for this, but since this is quite dependent on the package manager being used and the project structure I think that adding an e2e would be tricky (e.g. I'd have to force pnpm to put some dependecies in some …
=> adjust wrangler patching logic to use the correct `node_modules/next/dist` directory

.github/workflows/checks.yml, .github/workflows/playwright.yml, package.json, packages/cloudflare/env.d.ts, packages/cloudflare/package.json, packages/cloudflare/src/api/get-cloudflare-context.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-chunk-installation-identifiers.ts, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts, packages/cloudflare/src/cli/templates/worker.ts, packages/cloudflare/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml
- improved the workflows for checks + e2es.
- stricter tsconfig rules.
- type declarations for process.env.
- better types for fetch handler.
=> chore: improve tsconfig strictness and ci workflows

packages/cloudflare/src/cli/build/build-worker.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-middleware-manifest-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-exception-bubbling.ts
Changes:
- Removes the `NEXT_PRIVATE_MINIMAL_MODE` env var.
- Inlines the middleware manifest instead of it being dynamic require.
- Removes the no fallback exception bubbling as this results in hanging promises when SSG routes disable fallback dynamic params.
---
We currently enable the private version of minimal mode, alongside the public version of minimal mode. This is problematic as it is intended to be used by cloud providers when they have an additional layer on top of the worker that handles routing systems, cdn caching, static routes, etc.. That's why Vercel uses it. As a result, we're disabling specific behaviour without building our own system that will handle that.
There's two ways to look at this;
1. Enable the internal minimal mode -> build our own routing system, cdn …
=> feat: use incremental cache during rendering

.changeset/serious-buckets-wink.md, .github/workflows/changesets.yml
I got carried away and assumed that the default publish in changesets-action would do the pnpm publish automatically.
But actually we do need to provide that here.
=> ci: actually publish updates packages to npm

packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-next-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts
=> fix: Windows support

.changeset/yellow-cougars-explain.md, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, packages/cloudflare/src/cli/config.ts
**Changes**
- Defaults the `__OPENNEXT_KV_BINDING_NAME` env var to the default kv name.
- The typescript types mark this variable as defined due to its use for inlining in the cache handler, so defaulting the env var itself makes sense I think.
- Uses the env var in the config for the kv name.
- Adds more context to the cache handler patch.
docs pr: https://github.com/opennextjs/docs/pull/24
=> feat: configure kv binding name with env var

.changeset/swift-geckos-turn.md, packages/cloudflare/src/cli/index.ts
Fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/82
Expanded the error to point towards adding the next.config to run the application.
=> Expand missing next.config error message

packages/cloudflare/TODO.md, packages/cloudflare/src/cli/build/build-next-app.ts
Update the `sst/open-next` URLs into  `opennextjs/opennextjs-aws` to represent the recent changes
=> Update the sst urls

packages/cloudflare/src/cli/build/build-worker.ts, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, packages/cloudflare/src/cli/build/utils/copy-prerendered-routes.ts, packages/cloudflare/src/cli/config.ts, packages/cloudflare/src/cli/index.ts
**Context**
We have what seems to be a pre-options and then options. It would help in the long-term to have a single set of options that we use to stub the project setup and the config creation, especially if we add more CLI options in the future. Therefore, the types are slightly refactored to share the same thing between the creation of the project config and the project setup function.
I don't mind if you want to keep it as is, but I think it would be simpler to have a single object used between the two.
I wanted to move the config creation to before the project setup outside but it currently depends on the build happening in order to generate the config unfortunately for the .next server directory.
**Changes**
- Shares the same input between the two.
- Renames `builderOutput` to …
=> refactor: project options type shared with build + config init

.changeset/nine-impalas-wave.md, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, packages/cloudflare/src/cli/config.ts, packages/cloudflare/src/cli/index.ts
Introduces a CLI arg to let people choose to disable minification (e.g. for debugging purposes).
Only applies to the cache handler at the moment as that's the only part being minified currently.
=> feat: cli arg to disable minification

packages/cloudflare/src/cli/build/build-worker.ts, packages/cloudflare/src/cli/build/patches/investigated/copy-package-cli-files.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/index.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-middleware-manifest-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-next-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-find-dir.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts, packages/cloudflare/src/cli/build/utils/index.ts, packages/cloudflare/src/cli/build/utils/normalize-path.ts, packages/cloudflare/src/cli/config.ts
**Context**
We're inconsistent with how we use default imports with node:path vs every other import in the codebase.
**Changes**
- Pulls the path normalization out into a utility.
- Replaces the path default import with importing the actual stuff that's used.
=> refactor: use join instead of path.join

packages/cloudflare/eslint.config.mjs, packages/cloudflare/package.json, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/build/build-next-app.ts, packages/cloudflare/src/cli/build/build-worker.ts, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/build/patches/investigated/copy-package-cli-files.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-chunk-installation-identifiers.test.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-file-content-with-updated-webpack-f-require-code.test.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-updated-webpack-chunks-file-content.test.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/get-updated-webpack-chunks-file-content.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/index.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-middleware-manifest-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-next-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-find-dir.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts, packages/cloudflare/src/cli/build/utils/copy-prerendered-routes.ts, packages/cloudflare/src/cli/build/utils/index.ts, packages/cloudflare/src/cli/build/utils/read-paths-recursively.ts, packages/cloudflare/src/cli/config.ts, packages/cloudflare/src/cli/index.ts, packages/cloudflare/src/cli/templates/cache-handler/open-next-cache-handler.ts, packages/cloudflare/src/cli/templates/cache-handler/utils.ts, packages/cloudflare/src/cli/templates/worker.ts, packages/cloudflare/tsup.config.ts, pnpm-lock.yaml
The previously used `sort-imports` can not fix the code.
Changed the plugins to ones that can auto-fix the code (i.e. on save, or via `lint:fix`). 
Getting an error without auto-fix was becoming frustrating.
=> feat: Update ESLint config to fix imports/exports

packages/cloudflare/src/cli/build/build-worker.ts, packages/cloudflare/src/cli/build/patches/investigated/copy-package-cli-files.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, packages/cloudflare/src/cli/build/patches/investigated/update-webpack-chunks-file/index.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-middleware-manifest-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/inline-next-require.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-find-dir.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts, packages/cloudflare/src/cli/build/utils/copy-prerendered-routes.ts, packages/cloudflare/src/cli/config.ts
**Context**
Source and output paths are currently mixed in the config with no clear distinction
**Changes**
- Restructures config types into separate objects for source paths vs output paths vs internal paths.
=> refactor: improve separation of source / output paths in config

.github/workflows/prereleases.yml, README.md
> [!note]
> this PR is matching what I am doing here: https://github.com/opennextjs/opennextjs-aws/pull/614
=> add branch prereleases

examples/middleware/app/layout.tsx, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/templates/worker.ts, pnpm-lock.yaml
Update the lock file
Format the files
=> fix: fox CI errors 🦊

benchmarking/.gitignore, benchmarking/README.md, benchmarking/package.json, benchmarking/src/benchmarking.ts, benchmarking/src/cloudflare.ts, benchmarking/src/index.ts, benchmarking/src/utils.ts, benchmarking/tsconfig.json, package.json, pnpm-lock.yaml, pnpm-workspace.yaml
As discussed with the team we want to look into application performance improvements, but before doing that it's important to know where we start, so we can also validate our solutions and see if we are actually improving things.
So for this I'm introducing here some rudimental benchmarking capabilities that rely on our `examples`.
The `benchmark` script I'm adding here allows any user (including external contributors) to log in using wrangler, deploy and benchmark the example applications.
The benchmarking here simply consists in `fetch`ing from the deployed application and seeing how long the fetch took (using `performance.now()` calls).
This is the result of running the script (`pnpm benchmark` at the root of the monorepo):
<details>
<summary>`2024-11-01_16-41-33.json.json`</summary> …
=> implement example apps benchmarking

packages/cloudflare/src/cli/build/build-worker.ts, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/templates/worker.ts
- Rely on OpenNext to copy the static assets
- Remove useless code in the worker - assets are served when path matches
=> feat: integrate OpenNext static assets

packages/cloudflare/env.d.ts, packages/cloudflare/package.json, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts, pnpm-lock.yaml, pnpm-workspace.yaml
This is required to apply string replacement patches.
Fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/143
=> fix(build): Do not minify OpenNext bundles

packages/cloudflare/package.json, pnpm-lock.yaml
Pull in `@opennextjs/aws` changes for https://github.com/opennextjs/opennextjs-cloudflare/issues/147
Updating wrangler will be the next step (see https://github.com/cloudflare/workers-sdk/pull/7431)
=> chore: bump @opennextjs/aws

pnpm-lock.yaml, pnpm-workspace.yaml
wrangler 3.93.0 has an updated unenv using the native workerd stream implementation. It fixes an issue with server actions.
Ref:
- https://github.com/opennextjs/opennextjs-cloudflare/issues/147
- https://github.com/unjs/unenv/pull/363
=> chore(wrangler): bump to ^3.93.0

packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-load-instrumentation-module.ts
resolves #160 
___
This PR patches the bundled worker code by removing the content of all the problematic `loadInstrumentationModule` methods.
Such removal however most likely breaks [Next.js' instrumentation](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation), so I think that it should just be considered a temporary workaround for supporting Next.js 15.
=> temporary patch the `loadInstrumentationModule` methods to support Next.js 15

.github/ISSUE_TEMPLATE/1.bug_report.yml
Quite minor but I don't think we should ask for the node version since that's already included in the [`next info` output]( https://github.com/opennextjs/opennextjs-cloudflare/blob/021ddb7ef630e0162b9fb55226b82ce6bfd13efc/.github/ISSUE_TEMPLATE/1.bug_report.yml?plain=1#L64-L71) and both fields are required.
Alternatively we could make the `next info` field not required.
=> remove node-version field from the GitHub bug issue template

examples/api/open-next.config.ts, examples/api/wrangler.toml, examples/create-next-app/open-next.config.ts, examples/create-next-app/wrangler.toml, examples/vercel-blog-starter/open-next.config.ts, examples/vercel-blog-starter/wrangler.toml, examples/vercel-commerce/open-next.config.ts, examples/vercel-commerce/wrangler.toml, packages/cloudflare/src/cli/build/bundle-server.ts, pnpm-lock.yaml, pnpm-workspace.yaml
See https://github.com/cloudflare/workerd/issues/3245 for details/rationale about the fix.
Updated the examples.
The blog and commerce examples fails, I'll create separate issues for them.
-> See #174 and #175, both added to the board.
=> Fix + update examples

packages/cloudflare/package.json, pnpm-lock.yaml
patch from https://github.com/opennextjs/opennextjs-aws/pull/678
resolves #177
=> fix: solve __import_unsupported Next.js 15 issue by bumping the `@opennextjs/aws` dependency

packages/cloudflare/src/cli/build/patches/to-investigate/patch-find-dir.ts
resolves #172 
___
The `patchFindDir` function: https://github.com/opennextjs/opennextjs-cloudflare/blob/acec1c3ce61602a5bbb3f1330b5d1e0d0110b3f6/packages/cloudflare/src/cli/build/patches/to-investigate/patch-find-dir.ts#L12
Stopped working since a new `name` variable got introduced in the Next.js source code, causing the bundled code to rename the function's `name` parameter to `name2` instead:
I fixed this by updating the code replacement to also accept the variables with a numerical suffix. I also added a check to make sure that the patching is applied (if we already had the check in place that would have saved me lots of time here! 😭)
A few notes:
- I wanted to update the code to use AST manipulation, but since this patch is in the `to-investigate` directory I guess that we assume …
=> make sure `patchFindDir` works with Next.js 15 and add patching validation check

packages/cloudflare/src/cli/build/bundle-server.ts
=> patch `eval("require")` calls to avoid runtime warnings

packages/cloudflare/src/cli/build/bundle-server.ts
The e2es are currently failing to run due to the eval patch not being required for Next.js 14 (which the e2es are currently using).
This PR makes that patch optional, i.e. doesn't throw an error if the patch hasn't made any changes.
=> prevent eval patch from failing build

packages/cloudflare/package.json
I'm trying to write a script that works alongside my Next.js project, and since Next.js is still CJS - I'm unable to use `"type": "module"` in my package.json
This package is required as part of my database setup, and it even works outside Next.js, but for whatever cursed CJS → ESM compat reason, I can't import it.
default is a generic fallback - and allows me to import it.
=> add default to exports

packages/cloudflare/README.md, packages/cloudflare/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Fix a KI when browser cache was enabled by pulling the fix from https://github.com/opennextjs/opennextjs-aws/pull/683
=> fix: No body for 101, 204, 205, or 304 status code

.changeset/nine-fireants-protect.md, examples/middleware/app/clerk/route.ts, examples/middleware/e2e/base.spec.ts, examples/middleware/middleware.ts, examples/middleware/package.json, packages/cloudflare/src/cli/build/bundle-server.ts, pnpm-lock.yaml
=> fix: CustomRequest instantiation

.changeset/khaki-shirts-deliver.md, packages/cloudflare/src/cli/build/bundle-server.ts
Fix an issue with NextAuth (#206)
Creating a PR so that users can test, but need to come with a proper test
=> fix: delete init.cache rather than assign undefined

.changeset/real-rings-walk.md, packages/cloudflare/package.json, pnpm-lock.yaml
A quick (potentially temporary) solution for the `process.env.NODE_ENV` warning:
___
This change consists in simply bumping the aws dependency to its prerelease package generated in https://github.com/opennextjs/opennextjs-aws/pull/686 ([comment](https://github.com/opennextjs/opennextjs-aws/pull/686#issuecomment-2564340650))
=> remove `process.env.NODE_ENV` warning by bumping `@opennextjs/aws` dependency

.changeset/lazy-balloons-report.md, .prettierrc, packages/cloudflare/env.d.ts, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/build/index.ts, packages/cloudflare/src/cli/config.ts, packages/cloudflare/src/cli/index.ts, packages/cloudflare/templates/defaults/wrangler.jsonc, packages/cloudflare/templates/defaults/wrangler.toml
Similarly to https://github.com/opennextjs/opennextjs-cloudflare/pull/193 I thought it'd be a nice touch if we created the `wrangler.toml` file for the user instead of telling them to create and populate it themselves 🙂 
___
Related docs update: https://github.com/opennextjs/docs/pull/45
=> create a wrangler config file for the user in case one is not already present (alongside ways to opt out of this)

.changeset/bright-parents-juggle.md, packages/cloudflare/src/cli/build/utils/extract-project-env-vars.spec.ts, packages/cloudflare/src/cli/build/utils/extract-project-env-vars.ts
Align the behavior with [what NextJs does](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#test-environment-variables)
=> fix: exclude `.env.local` files for `test` mode

.changeset/cold-plants-deliver.md, packages/cloudflare/src/cli/build/patches/to-investigate/patch-exception-bubbling.ts
fixes #221 
The `nextBubbleNoFallback` patch needs updating since the code has been changed in the Next.js source, this PR updates the patch by supporting the current and canary code
> [!Important]
> I am pretty sure this change is correct but I could not validate it properly since I tested it with a simple hello-world app using `next@15.2.0-canary.0` and with the new patch applied the error does disappears but the app still doesn't work since some other (unrelated) errors pop up
>
> note that this patch is under `to-investigate` so it might be ok to just progress with this and investigate/validate it more properly whenever possible
=> update the `patchExceptionBubbling` patch

.changeset/silly-phones-accept.md, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts
wrap `require("react-dom/server.edge")` calls in `pages.runtime.prod.js` in `try-catch`es so that esbuild won't fail when encountering them, this doesn't guarantee that things won't blow up at runtime though
___
fixes #119
=> patch `require("react-dom/server.edge")` calls in `pages.runtime.prod.js` so that they are `try-catch`ed

packages/cloudflare/src/cli/templates/worker.ts
We already test at the call site
```ts
if (process.env.__PROCESS_ENV_POPULATED !== "1") {
await populateProcessEnv(url, env.NEXTJS_ENV);
process.env.__PROCESS_ENV_POPULATED = "1";
}
```
=> refactor: remove uneeded check

.changeset/short-cats-kneel.md, examples/api/app/api/request/route.ts, examples/api/e2e/base.spec.ts, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts
fixes #210
Research into what happens internally in Next.js is available in https://github.com/opennextjs/opennextjs-cloudflare/issues/210#issuecomment-2573260525.
OpenNext is removing the `trustHostHeader: true` option from the Next.js config if routing is disabled, and it considers routing disabled when `config.middleware.external` is truthy. This value is required to be true in the OpenNext config used for deploying to Cloudflare.
This PR changes the check to not strip it if there is external middleware.
=> fix: host not included in route handler urls

.changeset/lemon-zoos-chew.md, packages/cloudflare/src/api/get-cloudflare-context.ts
I opted for an environment variable as it was the closest to the `--env` flag that you'd use with wrangler.  I also considered exposing it as via an API method and saving the result in a module level variable as well as a global variable, but I figured keeping this configuration as close to how you'd do in wrangler made the most sense.  Happy to discuss though!
Addresses #239
=> Add support for wrangler environment selection in next dev mode

.changeset/slow-plants-boil.md, packages/cloudflare/package.json, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-cache.ts, pnpm-lock.yaml
Changes some instances of inlined paths to use the normalizePath helper (the cache one was the main problem) and updates an esbuild filter.
Bumps aws package to use the prerelease in https://github.com/opennextjs/opennextjs-aws/pull/695 to fix the esbuild filters.
fixes #204
fixes #236
=> fix: invalid paths in windows bundles

examples/middleware/e2e/base.spec.ts
=> replace incorrect `expect` calls with `await` in middleware e2es

examples/api/wrangler.json, examples/create-next-app/wrangler.json, examples/middleware/.env, examples/middleware/wrangler.json, examples/vercel-blog-starter/wrangler.json, examples/vercel-commerce/wrangler.json, packages/cloudflare/templates/defaults/wrangler.json
`CLERK_ENCRYPTION_KEY` is added to fix an error log during e2e
=> refactor: add wrangler chema, fix CLERK error

.changeset/rare-hornets-shake.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts
Migrates our esbuild filter usage to use the new utility.
=> refactor: use the new regex utility for cross-platform paths

packages/cloudflare/src/cli/build/patches/ast/optional-deps.spec.ts, packages/cloudflare/src/cli/build/patches/ast/optional-deps.ts, packages/cloudflare/src/cli/build/patches/ast/util.spec.ts, packages/cloudflare/src/cli/build/patches/ast/util.ts
=> test: add unit test for the optional dependency patch

packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts, packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts, packages/cloudflare/src/cli/build/utils/create-config-files.ts, packages/cloudflare/src/cli/config.ts
=> refactor: join join arguments

packages/cloudflare/package.json, pnpm-lock.yaml
Hi OpenNext team. Thanks for adopting ast-grep as its tooling.
ast-grep/napi recently improved the packaging system and reduced the package size by 80%+.
See [this tweet](https://x.com/hd_nvim/status/1883395941681832057)
I hope this version bump can help end users having a better DX.
I don't think this change should result in a version bump, so no changeset is added.
=> chore: update ast-grep/napi's version to reduce package size

.changeset/quick-timers-fail.md, .github/workflows/checks.yml, .github/workflows/playwright.yml, .github/workflows/prereleases.yml, examples/api/app/og/route.tsx, examples/api/e2e/base.spec.ts, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/ast/optional-deps.ts, packages/cloudflare/src/cli/build/patches/ast/util.ts, packages/cloudflare/src/cli/build/patches/ast/vercel-og.spec.ts, packages/cloudflare/src/cli/build/patches/ast/vercel-og.ts, packages/cloudflare/src/cli/build/patches/investigated/index.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-vercel-og-library.spec.ts, packages/cloudflare/src/cli/build/patches/investigated/patch-vercel-og-library.ts
PR is based off of #282 and should not be merged before that one.
This PR does the following:
- Changes the function for getting rule edits to also enable returning matches.
- Patches the import of `index.node.js` to `index.edge.js`.
- Patches the fallback font fetch to use an import.
- Renames the fallback font to be suffixed with `.bin`.
- Copies the edge version to the OpenNext `node_modules`.
- Unit tests + e2e test.
Might be worth noting that the edge runtime version is only available in the node_modules location referenced by the traced files in .next/server, and not .next/standalone. So we need to use that output to get the edge file and work our way back up to node_modules, and bring that over the right place for the standalone build in our output.
Not sure if this approach is …
=> fix: patch @vercel/og usage to use the edge runtime version

.changeset/friendly-ears-ring.md, packages/cloudflare/src/api/cloudflare-context.ts
Currently calling `initOpenNextCloudflareForDev()` in the Next.js config file causes this initialization logic to run twice, consuming more resources and causing extra noise in the terminal logs, this change makes sure that the initialization logic is run only once instead
fixes half of #288
=> fix: make sure that the `initOpenNextCloudflareForDev()` logic runs only once

examples/e2e/app-router/.gitignore, examples/e2e/app-router/e2e/after.test.ts, examples/e2e/app-router/e2e/api.test.ts, examples/e2e/app-router/e2e/config.redirect.test.ts, examples/e2e/app-router/e2e/headers.test.ts, examples/e2e/app-router/e2e/host.test.ts, examples/e2e/app-router/e2e/image-optimization.test.ts, examples/e2e/app-router/e2e/isr.revalidate.test.ts, examples/e2e/app-router/e2e/isr.test.ts, examples/e2e/app-router/e2e/middleware.cookies.test.ts, examples/e2e/app-router/e2e/middleware.redirect.test.ts, examples/e2e/app-router/e2e/middleware.rewrite.test.ts, examples/e2e/app-router/e2e/modals.test.ts, examples/e2e/app-router/e2e/og.test.ts, examples/e2e/app-router/e2e/parallel.test.ts, examples/e2e/app-router/e2e/playwright.config.ts, examples/e2e/app-router/e2e/query.test.ts, examples/e2e/app-router/e2e/revalidateTag.test.ts, examples/e2e/app-router/e2e/serverActions.test.ts, examples/e2e/app-router/e2e/sse.test.ts, examples/e2e/app-router/e2e/ssr.test.ts, examples/e2e/app-router/e2e/trailing.test.ts, examples/e2e/app-router/package.json, examples/e2e/app-router/tsconfig.json, examples/e2e/utils.ts, pnpm-lock.yaml
Run the tests with `pnpm -F app-router e2e-fix`
Note that the script is named `e2e-fix` so that it doesn't run on the CI yet as some tests are failing. 
Some failures are expected (i.e. ISR) and some need to be investigated.
=> test: import app-router e2e tests from aws

.changeset/fresh-walls-hug.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/ast/optional-deps.spec.ts, packages/cloudflare/src/cli/build/patches/ast/optional-deps.ts, packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts
The second commits adds `critters` and `react-dom/server.edge` to the list of optional dependencies.
Note that I didn't re-use the comment from `wrangler-deps.ts` for `react-dom/server.edge` as it was not fully accurate. `pages.runtime.prod.js` does actually wrap the import in the same way as [Next.js](https://github.com/vercel/next.js/blob/6784575/packages/next/src/server/ReactDOMServerPages.js):
```ts
"./dist/server/ReactDOMServerPages.js":(e,t,r)=>{"use strict";let n;try{n=r("react-dom/server.edge")}catch(e){if("MODULE_NOT_FOUND"!==e.code&&"ERR_PACKAGE_PATH_NOT_EXPORTED"!==e.code)throw e;n=r("react-dom/server.browser")}e.exports=n}
```
The problem is when the package is re-exported:
```ts
e=>{"use strict";e.exports=require("react-dom/server.edge")}
```
This last site will be patched by …
=> refactor: Make the list of optional dependencies configurable

.changeset/pretty-boats-invent.md, pnpm-lock.yaml, pnpm-workspace.yaml
This change makes sure that `next dev` doesn't produce multiple logs saying `Using vars defined in .dev.vars`, as that was a wangler bug fixed in 3.107.0 (and we include wrangler as a peer dependency of the package)
___
fixes #288
=> bump wrangler to `^3.107.0`

examples/e2e/app-router/e2e/after.test.ts, examples/e2e/app-router/e2e/host.test.ts, examples/e2e/app-router/e2e/image-optimization.test.ts, examples/e2e/app-router/e2e/isr.revalidate.test.ts, examples/e2e/app-router/e2e/isr.test.ts, examples/e2e/app-router/e2e/revalidateTag.test.ts, examples/e2e/app-router/e2e/ssr.test.ts, examples/e2e/app-router/e2e/trailing.test.ts, examples/e2e/app-router/open-next.config.ts, examples/e2e/app-router/package.json, examples/e2e/app-router/wrangler.json
this change renames the `e2e-fix` script of the `e2e/app-router` app to just `e2e` so that it is included as part of our CI checks, in order for it not to fail some tests have been skipped (with appropriate comments explain why)
__
Part of #291
=> enable `e2e/app-router` tests to run in CI

.changeset/brave-pandas-add.md, packages/cloudflare/src/api/cloudflare-context.ts
`getCloudflareContext` can't be used in static routes, currently a misleading error
message incorrectly tells the developer that they haven't called `initOpenNextCloudflareForDev`
in their config file, this change updates such error message to properly clarify what
the issue is (and how to solve it)
___
fixes #317
=> fix: provide a proper error message when using `getCloudflareContext` in static routes

examples/e2e/app-pages-router/e2e/host.test.ts, examples/e2e/app-pages-router/e2e/image-optimization.test.ts, examples/e2e/app-pages-router/e2e/isr.test.ts, examples/e2e/app-pages-router/e2e/pages_isr.test.ts, examples/e2e/app-pages-router/package.json
this change renames the `e2e-fix` script of the `e2e/app-pages-router` app to just `e2e` so that it is included as part of our CI checks, in order for it not to fail some tests have been skipped (with appropriate comments explain why)
____
Part of #291
=> enable e2e/app-pages-router tests to run in CI

examples/e2e/pages-router/e2e/isr.test.ts, examples/e2e/pages-router/next.config.ts, examples/e2e/pages-router/package.json
this change renames the `e2e` script of the `e2e/pages-router` app to just `e2e` so that it is included as part of our CI checks, in order for it not to fail one test has been skipped (with an appropriate comment explain why)
___
related to https://github.com/opennextjs/opennextjs-cloudflare/issues/291
=> enable e2e/pages-router tests to run in CI

packages/cloudflare/env.d.ts, packages/cloudflare/src/cli/build/open-next/compile-env-files.ts, packages/cloudflare/src/cli/templates/worker.ts
- move the generated file to an env folder
- use a local variable to load once (vs a key of process.env)
=> refactor: Next env loading

.changeset/curly-mice-agree.md, packages/cloudflare/src/api/kvCache.ts
Hi :wave:,
I noticed the typo during a build output, and I think this wanted to be the `cdn-cgi` special cf path.
=> fix: use intended asset cache dir

packages/cloudflare/src/cli/build/patches/plugins/require-page.ts
ESBuild plugin should be async: https://esbuild.github.io/plugins/#on-load
=> refactor: make inlineRequirePagePlugin async

.changeset/fluffy-taxis-rescue.md, .changeset/spotty-baboons-rule.md, packages/cloudflare/package.json, packages/cloudflare/src/api/kvCache.ts, pnpm-lock.yaml
This change makes sure that stale cache values from assets are not served when there is no KV binding.
This makes the issue in https://github.com/opennextjs/opennextjs-cloudflare/issues/328 no longer flaky (it makes the test always fail) since before it was passing because stale cache values were being served from assets (so the fetch cached result would always stay the same, making this [check](https://github.com/opennextjs/opennextjs-cloudflare/blob/420b598ac242ff91768685d312c9940335f3a120/examples/e2e/app-router/e2e/ssr.test.ts#L37) pass). The reason why KV is not being used is still being investigated.
No other tests besides the [328 one](https://github.com/opennextjs/opennextjs-cloudflare/blob/420b598ac242ff91768685d312c9940335f3a120/examples/e2e/app-router/e2e/ssr.test.ts#L31-L38) …
=> Do not serve stale values from the assets when there is no KV

.changeset/fifty-parrots-retire.md, packages/cloudflare/src/cli/utils/ask-confirmation.ts
When using opennextjs-cloudflare under node18, I get the following error in “crypto”.
```
file:///home/nojiri/yourself-score/node_modules/@opennextjs/cloudflare/dist/cli/utils/ask-confirmation.js:3
const questionName = crypto.randomUUUID();
ReferenceError: crypto is not defined
```
Until node@v18 is deprecated, we think it's ok to import.
=> fix:Crypto works under node18

packages/cloudflare/src/cli/build/patches/plugins/content-updater.ts, packages/cloudflare/src/cli/build/patches/plugins/load-instrumentation.ts, packages/cloudflare/src/cli/build/patches/plugins/require-page.ts, packages/cloudflare/src/cli/build/patches/plugins/require.ts
It is used as a fast heuristics to trigger the update
=> refactor(ContentUpdater): add a filterContent argument

examples/playground/app/api/env/route.ts, examples/playground/app/isr/[id]/dynamic/page.tsx, examples/playground/app/isr/[id]/no-dynamic/page.tsx, examples/playground/app/isr/[id]/page.tsx, examples/playground/e2e/isr.spec.ts, examples/playground/open-next.config.ts, examples/playground/wrangler.json
This works as epxected with `pnpm dev` (Next server):
http://localhost:3000/isr/1 (and 2, 3) returns the page, 4 and up return a 404
with `pnpm preview`, http://localhost:8787/isr/N always return a 404
```text
[wrangler:inf] GET /isr/1 404 Not Found (69ms)
```
@conico974 any idea what's going on here?
=> Add an isr route to the playground

.changeset/selfish-bananas-nail.md, packages/cloudflare/src/utils/get-package-templates-dir-path.ts
fix: #358
Make references to the template `open-next.config.ts` correct.
=> fix:path to file template in open-next.config.ts

.changeset/few-ducks-listen.md, examples/e2e/app-router/e2e/ssr.test.ts, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/plugins/content-updater.ts, packages/cloudflare/src/cli/build/patches/plugins/fetch-cache-wait-until.spec.ts, packages/cloudflare/src/cli/build/patches/plugins/fetch-cache-wait-until.ts
Next.js does not await promises that update the incremental cache for fetch requests,
that is needed in our runtime otherwise the cache updates get lost, so this change
makes sure that the promise is properly awaited via `waitUntil`
___
resolves #328
=> fix: make sure that fetch cache sets are properly awaited

examples/common/apps.ts, examples/playground/e2e/playwright.config.ts, examples/playground/e2e/playwright.dev.config.ts
=> refactor(e2e): rename api to playground

.changeset/modern-dancers-rescue.md, examples/next-partial-prerendering/next.config.js, packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts
fixes #376 
In some monorepo projects when running build there is a node_modules inside `server-functions` but not inside `server-functions/{projectPath}`.
This change to check for the existence of the package-scoped node_modules before choosing it over the non-package-scoped one.
Not quite sure how simple it would be to add an e2e for this because it's dependent on the monorepo structure and I believe it would be hit for us due to having multiple apps
=> fix: vercel og patch not moving to right node_modules directory

packages/cloudflare/src/cli/build/open-next/createServerBundle.ts
This file is a copy-edit of an aws file.
The PR syncs a fix + a refactor
=> fix: sync createServerBundle.ts with aws

examples/e2e/app-pages-router/e2e/isr.test.ts, examples/e2e/app-pages-router/e2e/pages_isr.test.ts, examples/e2e/app-pages-router/open-next.config.ts, examples/e2e/app-pages-router/wrangler.json, examples/e2e/pages-router/e2e/isr.test.ts, examples/e2e/pages-router/open-next.config.ts, examples/e2e/pages-router/wrangler.json
enable cache/queue and un`skip` passing tests
=> chore: unskip more isr e2es

.changeset/ten-mangos-rush.md, packages/cloudflare/src/cli/build/patches/plugins/eval-manifest.ts, packages/cloudflare/src/cli/build/patches/plugins/find-dir.ts, packages/cloudflare/src/cli/build/patches/plugins/load-manifest.ts, packages/cloudflare/src/cli/build/patches/plugins/require-page.ts
The PR title/changeset is a bit vague because I didn't actually tested on windows.
But I believe this PR will improve, i.e.:
- https://github.com/cloudflare/workers-sdk/issues/8159
- https://github.com/opennextjs/opennextjs-cloudflare/issues/321#issuecomment-2646200860
What this PR does is to normalize the path variables vs only the constants those are compared to.
=> fix: improve windows support

.changeset/warm-lizards-lick.md, packages/cloudflare/src/api/cloudflare-context.ts
currently `getCloudflareContext` run in sync mode at the top level of a not static route
gives a misleading error message saying that the function needs to be run in a not static
route, the changes here correct this error message clarifying that the problem actually is
fixes  #382
=> fix incorrect (sync) `getCloudflareContext` error message

examples/e2e/app-router/e2e/sse.test.ts, examples/e2e/app-router/e2e/ssr.test.ts
I'm pretty sure I was getting this test failing both locally and in CI, but now everything seems to be working just fine... 🤔
_____
fixes #313
=> un-skip the ssr loading e2e test in the `app-router` app

.changeset/long-items-poke.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/plugins/patch-depd-deprecations.spec.ts, packages/cloudflare/src/cli/build/patches/plugins/patch-depd-deprecations.ts
Some dependencies of Next.js (`raw-body` and `send`) use `depd` to deprecate some of their functions,
`depd` uses `eval` to generate a deprecated version of such functions, this causes `eval` warnings in
the terminal even if these functions are never called, the changes here by patching the depd `wrapfunction`
function so that it still retains the same type of behavior but without using `eval`
fixes #291
=> remove `eval` calls introduced by `depd` wrapped functions

.changeset/ten-flowers-begin.md, packages/cloudflare/src/cli/build/bundle-server.ts
jonkwheeler reported on Discord that there is an error with `__filename` not being defined, this should help
=> define __filename

.changeset/warm-dragons-search.md, packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts, packages/cloudflare/src/cli/build/patches/plugins/eval-manifest.ts, packages/cloudflare/src/cli/build/patches/plugins/load-manifest.ts
relates to #321 
node:path's join on windows uses `\\` separator but node-glob by default accepts only `/`
=> fix: manifest glob on windows

packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/templates/shims/fetch.ts
currently in our bundle we include the `next/dist/compiled/node-fetch` package, this doesn't seem actually necessary and it introduces a good amount of unnecessary code in our bundle, moreover it also causes a warning in the terminal (because of an === -0 comparison), the changes here replace the node-fetch code with a simply shim that re-exports the native fetch
___
Notes:
- by looking at the Next.js source code I wouldn't really tell why node-fetch is used, I can only imagine that it's there for either backward compatibility or brought in as part of some dependencies
- all the Next.js source code that would import from node-fetch that I've found always only imports just the default export
- I couldn't find a way to trigger a Next.js app to call node-fetch (as far as I can tell it's …
=> shim `next/dist/compiled/node-fetch`

.changeset/cold-numbers-bow.md, .changeset/lovely-bugs-flow.md, examples/bugs/gh-119/open-next.config.ts, examples/bugs/gh-219/open-next.config.ts, examples/bugs/gh-223/open-next.config.ts, examples/create-next-app/open-next.config.ts, examples/e2e/app-pages-router/open-next.config.ts, examples/e2e/app-router/open-next.config.ts, examples/e2e/pages-router/open-next.config.ts, examples/middleware/open-next.config.ts, examples/next-partial-prerendering/open-next.config.ts, examples/playground14/open-next.config.ts, examples/playground15/open-next.config.ts, examples/ssg-app/open-next.config.ts, examples/vercel-blog-starter/open-next.config.ts, examples/vercel-commerce/open-next.config.ts, packages/cloudflare/package.json, packages/cloudflare/src/api/config.ts, packages/cloudflare/src/api/index.ts, packages/cloudflare/src/api/kvCache.ts, packages/cloudflare/templates/defaults/open-next.config.ts, pnpm-lock.yaml
this change adds a new `defineCloudflareConfig` utility that developers can use in their `open-next.config.ts` file to easily generate a configuration compatible with the adapter
___
Docs PR: https://github.com/opennextjs/docs/pull/84
___
resolves #114
=> add `defineCloudflareConfig` utility

examples/bugs/gh-119/next.config.ts, examples/bugs/gh-219/next.config.ts, examples/bugs/gh-223/next.config.mjs, examples/create-next-app/next.config.mjs, examples/middleware/next.config.mjs, examples/next-partial-prerendering/next.config.js, examples/playground14/next.config.mjs, examples/playground15/next.config.mjs, examples/ssg-app/next.config.ts, examples/vercel-blog-starter/next.config.mjs, examples/vercel-commerce/next.config.js
The typescript and eslint checks slow down our e2e builds while providing zero value. I would like to propose disabling them completely. The e2es we copied from aws already do this.
It's not a significant gain, but it cuts off about 15-20 seconds from time spent building apps.
=> chore: disable typescript + eslint during next.js builds

.changeset/famous-deers-attack.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/plugins/next-minimal.spec.ts, packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts, packages/cloudflare/src/cli/build/utils/index.ts, packages/cloudflare/src/cli/build/utils/needs-experimental-react.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Should fix #432 #373 and #333
Next 15.2 introduced a change that create an `AbortController` https://github.com/vercel/next.js/pull/73975/files as a const outside of the request context.
This `AbortController` cause an issue while requiring app router pages that makes all these require return `{}` instead of the actual module in workerd. (see the comment for more detail)
It also replace the define of `process.env.NEXT_MINIMAL` inside of esbuild by a custom plugin that keep the `renderHTML` that can be used as a fallback by Next in case of error.
It also bump next version to 15.2.0 for the e2e examples
It's a draft for now, if workerd is not expected to throw for this case we could remove almost everything in this PR and just bump wrangler once fixed and merged
=> Fix for next 15.2 and renderHTML should not be called in minimal mode

.changeset/spicy-seas-appear.md, examples/e2e/app-pages-router/wrangler.json, examples/e2e/app-router/wrangler.json, examples/e2e/pages-router/wrangler.json, packages/cloudflare/src/api/cloudflare-context.ts, packages/cloudflare/src/api/memory-queue.spec.ts, packages/cloudflare/src/api/memory-queue.ts
Service bindings are required for fetching the same worker in production.
A bit of a shame that our local e2es were unable to catch this as wrangler doesn't fail when doing fetches in local mode.
Docs PR - https://github.com/opennextjs/docs/pull/89
=> fix: deployed worker unable to invoke itself in memory queue

.changeset/smart-boxes-destroy.md, packages/cloudflare/src/cli/build/patches/ast/webpack-runtime.spec.ts, packages/cloudflare/src/cli/build/patches/ast/webpack-runtime.ts
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #452 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #451
=> fix: patch the webpack runtime when there is a single chunk

.changeset/pretty-lamps-press.md, examples/playground14/e2e/base.spec.ts, examples/playground14/pages/api/pages.ts, packages/cloudflare/package.json, packages/cloudflare/src/cli/build/patches/plugins/dynamic-requires.ts, pnpm-lock.yaml
fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/442
While the patch is the same, the path to the patched file is different in Next14 (`next/dist/server/future/helpers/module-loader/node-module-loader.js`). Update the patch to cover both Next14 (add test) and Next 15 (already tested)
=> fix: Pages router API routes with Next 14

examples/e2e/app-router/open-next.config.ts, examples/e2e/app-router/wrangler.jsonc, packages/cloudflare/package.json, packages/cloudflare/src/api/cloudflare-context.ts, packages/cloudflare/src/api/durable-objects/queue.spec.ts, packages/cloudflare/src/api/durable-objects/queue.ts, packages/cloudflare/src/api/durable-queue.ts, packages/cloudflare/src/api/memory-queue.spec.ts, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/templates/worker.ts, pnpm-lock.yaml
This PR implements a Durable Object for the Queue allowing proper deduplication of the ISR request.
I'll add handling of eventually consistent Incremental Cache (such as KV or using `withRegionalCache` from James PR) in another PR
The PR is split into 2 parts, this one and the one in #460 that add storage to it
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #460 
- <kbd>&nbsp;1&nbsp;</kbd> #459 👈
=> Durable Queue

.changeset/smart-bugs-play.md, examples/e2e/app-router/wrangler.jsonc, packages/cloudflare/src/api/cloudflare-context.ts, packages/cloudflare/src/api/durable-objects/queue.spec.ts, packages/cloudflare/src/api/durable-objects/queue.ts, packages/cloudflare/src/api/durable-queue.ts, packages/cloudflare/src/cli/build/build.ts, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/open-next/compileDurableObjects.ts, packages/cloudflare/src/cli/templates/worker.ts
It is a follow up of #459
It adds storage to the Durable object allowing it to better handle failure
It also allows it to handle eventually consistent incremental cache implementation by checking for every route if the route has been revalidated (Note that this does not cover On-Demand revalidation )
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #460 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #459
=> Durable Queue Storage

.changeset/tame-icons-shave.md, examples/e2e/app-router/package.json, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/build/build.ts, packages/cloudflare/src/cli/build/utils/index.ts, packages/cloudflare/src/cli/build/utils/populate-cache.ts, packages/cloudflare/src/cli/index.ts, packages/cloudflare/src/cli/project-options.ts
- Adds a CLI flag to enable auto-population of cache data for either local or remote.
- Adds a CLI flag to only populate cache (i.e. skip build completely).
- Populates D1 tag cache data when the adapter is used.
Docs PR and KV change to use auto-population will follow if we agree on this being the way forward
---
This is **part 1 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #479 
- <kbd>&nbsp;2&nbsp;</kbd> #443 
- <kbd>&nbsp;1&nbsp;</kbd> #436 👈
=> feat: auto-populating d1 cache data

.changeset/silver-baboons-begin.md, packages/cloudflare/src/api/cloudflare-context.ts, packages/cloudflare/src/api/durable-objects/queue.spec.ts, packages/cloudflare/src/api/durable-objects/queue.ts
Useful when the incremental cache data can be trusted (i.e. not eventually consistent)
=> Add an option for disabling sqlite on the durable object queue

.changeset/chilly-knives-taste.md, examples/common/config-e2e.ts, examples/overrides/r2-incremental-cache/package.json, examples/overrides/r2-incremental-cache/wrangler.jsonc, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/deploy/deploy.ts, packages/cloudflare/src/cli/populate-cache/populate-cache.ts, packages/cloudflare/src/cli/preview/preview.ts, packages/cloudflare/src/cli/utils/run-wrangler.ts
- Extracts the env flag's value from the passthrough args.
- Gives the value to the populate cache command.
=> feat: support passing the wrangler environment when populating the cache

.changeset/wise-gifts-sit.md, packages/cloudflare/src/cli/templates/worker.ts
We recommend using https://developers.cloudflare.com/images/transform-images/integrate-with-frameworks/ for cloudflare. However `/cdn-cgi/image/...` are not handled by `wrangler dev`.
What this PR does is serve the (original) images for `/cdn-cgi/image/...` urls.
I plan to improve the OpenNext docs, creating an HowTo referring to the page linked above.
_I created [a feature request](https://github.com/cloudflare/workers-sdk/issues/8637) for this to be implemented in miniflare._
=> Serve `/cdn-cgi/image/...` images in dev

packages/cloudflare/src/api/config.ts
minor cleanup/simplification.
There is some duplication but I think the code is simpler? (Couldn't get a generic `resolve` fn to work)
=> refactor: code cleanup

.changeset/modern-laws-happen.md, examples/e2e/app-router/open-next.config.ts, examples/e2e/app-router/package.json, examples/e2e/app-router/wrangler.jsonc, packages/cloudflare/src/api/cloudflare-context.ts, packages/cloudflare/src/api/do-sharded-tag-cache.spec.ts, packages/cloudflare/src/api/do-sharded-tag-cache.ts, packages/cloudflare/src/api/durable-objects/sharded-tag-cache.ts
Implements sharding replication for the Durable Object tag cache.
Instead of being sharded only based on the tag, each shard will now also be replicated
This allow to scale way more (virtually infinitely)
A single tag could be read from any of the N random replicas associated with the tag shard.
On write we still need to write to every single replicas associated with this tag shard
=> Feat Sharding Replication

.changeset/smooth-cups-allow.md, packages/cloudflare/package.json, packages/cloudflare/src/api/cloudflare-context.ts, packages/cloudflare/src/api/config.ts, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts, packages/cloudflare/src/cli/build/utils/ensure-cf-config.ts, packages/cloudflare/src/cli/index.ts, packages/cloudflare/src/cli/templates/worker.ts, pnpm-lock.yaml
This PR:
- Switch to using a bundled middleware - we were previsouly generating an external middleware but wrangler was bundling it together with the server bundle. We will revisit once we can deploy the middleware to a different worker.
- The server handler is now imported right before being used so that the env vars are guaranteed to be populated and the ALS initializzed.
Depends on https://github.com/opennextjs/opennextjs-aws/pull/798
=> refactor: switch to bundled middleware

.changeset/ten-parents-add.md, packages/cloudflare/src/cli/utils/run-wrangler.ts
Bun seems to be the only package manager that does not support `exec` in the same way. Instead, they use it for their built-in shell.
=> fix: bun failing to spawn wrangler

.changeset/strange-icons-camp.md, packages/cloudflare/src/cli/utils/run-wrangler.ts
Another package manager inconsistency. npm and yarn both need `--` to pass args to wrangler properly, whereas pnpm and bun will fail to pass args properly to wrangler if `--` is supplied...
=> fix: npm failing to pass args to wrangler

.changeset/little-seals-impress.md, packages/cloudflare/src/cli/build/bundle-server.ts
Fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/508
Full disclosure (also see issue above):
I don't know why this issue occurs. I just found this fix by experimenting. In the original situation, the worker detects the handler as a 'Getter', but if you use the 'handler' getter the result is undefined, but only on 'cold' boots. In a warm worker the Getter is initialized and it just works. By changing how we export in `handler.mjs` to a named export, it no longer detects it as a Getter but as a async function and it now works properly on cold boots. If someone could explain why this happens, please do!
=> fix: nextjs handler not detected in worker

.changeset/brave-snakes-roll.md, packages/cloudflare/src/cli/utils/run-wrangler.ts
Yarn classic and yarn modern appear to pass args around differently. Yarn modern uses the `packageManager` field in package.json, so this PR uses that to compare the semver to check if it's used or not.
=> fix: yarn v4 not passing args to wrangler correctly

.changeset/shaggy-bobcats-battle.md, packages/cloudflare/src/api/cloudflare-context.ts
To allow same behaviour as `setupDevPlatform()` from next-on-pages. In this case I assume the removal of passing options was not intended. If not, are there any alternatives to the below?
```ts
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";
initOpenNextCloudflareForDev({
persist: {
path: "../../.wrangler/state/v3/custom-dir",
},
});
```
When testing with ` pnpm --filter playground15 preview` the `.wrangler` directory is correctly created in the root of the project. But a `.wrangler` directory also appears within the playground15 directory. So I'm creating this PR so I can use a preview deployment to be able to test in my own app with D1. Or are there better ways to test in this repo itself?
=> feat: support passing options to init open-next cloudflare dev function

.changeset/cyan-ears-know.md, packages/cloudflare/src/cli/templates/worker.ts
fixes #333 
Jose (and other packages) relies on `process.version` and `process.versions.node`.
Defining them here until https://github.com/unjs/unenv/pull/493 is merged
/cc @petebacondarwin @mhart
=> Define `process.version` and `process.versions.node`

.changeset/popular-berries-deliver.md, packages/cloudflare/package.json, packages/cloudflare/src/api/overrides/incremental-cache/kv-incremental-cache.ts, packages/cloudflare/src/api/overrides/incremental-cache/r2-incremental-cache.ts, packages/cloudflare/src/cli/commands/populate-cache.ts, packages/cloudflare/src/cli/utils/run-wrangler.ts, pnpm-lock.yaml
=> Fix R2 bucket population

.changeset/rich-bears-kick.md, examples/e2e/app-router/app/isr/dynamic-params-false/[id]/page.tsx, examples/e2e/app-router/app/isr/dynamic-params-true/[id]/page.tsx, examples/e2e/app-router/e2e/isr.test.ts, examples/e2e/app-router/e2e/middleware.redirect.test.ts, examples/e2e/app-router/middleware.ts, examples/e2e/pages-router/e2e/streaming.test.ts, examples/e2e/pages-router/src/pages/api/streaming/index.ts, examples/e2e/pages-router/src/pages/sse/index.tsx
=> test: sync e2e with latest aws

.changeset/happy-bananas-buy.md, packages/cloudflare/src/api/overrides/incremental-cache/regional-cache.ts
This PR aims at improving the use of the regional cache by making sure that entries on it can be purged by cache-tag on Cloudflare.
In our application (https://github.com/GitbookIO/gitbook), we purge the cache both using `revalidateTag` but also using the Cloudflare API (https://developers.cloudflare.com/cache/how-to/purge-cache/purge-by-tags/).
I think this header has no negative impact on any other OpenNext users while unblocking us but also potentially unblocking someone who is using the long-lived cache and needs to quickly purge it (they could do it from the CF dashboard).
=> Set "cache-tag" on the regional cache entries

.changeset/light-insects-kiss.md, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/commands/upload.ts, packages/cloudflare/src/cli/index.ts
There are two ways to [create a new version](https://developers.cloudflare.com/workers/configuration/versions-and-deployments/#create-a-new-version) of a worker; immediate deployment with `wrangler deploy`, or gradual/delayed deployment with `wrangler versions upload`.
This adds a separate command called `opennextjs-cloudflare upload` that can be used to upload a new version of a worker.
=> feat: `upload` command for worker versions

.changeset/eleven-sloths-punch.md, packages/cloudflare/src/cli/build/build.ts, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/open-next/compile-env-files.ts, packages/cloudflare/src/cli/build/open-next/compile-init.ts, packages/cloudflare/src/cli/templates/init.ts, packages/cloudflare/src/cli/templates/worker.ts
I have been willing to do this for a long time...
The init code does not belong to the server bundle, it can be used for i.e. an external middleware.
Further benefits:
- We now have a way to inject values a build time via ESBuild defines, that will be useful for basePath support
- It will make it easier to add other entry points (scheduled, ...)
=> Extract the worker init code to a separate file

.changeset/blue-beds-crash.md, .changeset/silly-icons-battle.md, examples/bugs/gh-219/package.json, packages/cloudflare/package.json, packages/cloudflare/src/api/overrides/incremental-cache/kv-incremental-cache.ts, packages/cloudflare/src/api/overrides/incremental-cache/static-assets-incremental-cache.ts, packages/cloudflare/src/cli/build/build.ts, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/open-next/compile-init.ts, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts, packages/cloudflare/src/cli/templates/init.ts, packages/cloudflare/src/cli/templates/worker.ts, pnpm-lock.yaml
fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/416
The aws version bump fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/567
=> Add support for basePath

.changeset/twelve-turtles-trade.md, examples/playground14/e2e/head.spec.ts, examples/playground14/pages/head.tsx, examples/playground15/e2e/head.spec.ts, examples/playground15/pages/head.tsx, examples/playground15/tsconfig.json, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/plugins/pages-router-context.ts
Fix the shared context used in page router for versions of Next prior to 15.3
Fix #571
=> Fix pages router context

.changeset/thirty-camels-reflect.md, examples/e2e/app-pages-router/wrangler.jsonc, examples/playground14/wrangler.jsonc, packages/cloudflare/src/cli/commands/populate-cache.ts
- Changes to use `getPlatformProxy` for cache population prefix env vars
=> feat: use `getPlatformProxy` for cache population prefix vars

.changeset/famous-weeks-deliver.md, examples/playground15/instrumentation.js, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/templates/init.ts
It is expected that the global timers (i.e. `setInterval`, `setTimeout`) in Node returns a `Nodejs.Timeout` instead of a number. On cloudflare workers they return a number.
This can cause some unexpected crash like in #587, where sentry tries to call `unref()` on the created interval.
This PR fix #587
The only downsides to doing that is that in the middleware we'll have access to the Node version as well, but i don't think this is too big of an issue
=> Fix node timers

.changeset/wet-monkeys-look.md, packages/cloudflare/src/cli/args.ts, packages/cloudflare/src/cli/commands/deploy.ts, packages/cloudflare/src/cli/commands/populate-cache.ts, packages/cloudflare/src/cli/commands/preview.ts, packages/cloudflare/src/cli/commands/upload.ts
- Chunks assets for inserting to KV, defaulting to 25.
- Supports a custom chunk size with a CLI flag.
=> feat: bulk insert cache entries to KV

examples/e2e/pages-router/e2e/amp.test.ts, examples/e2e/pages-router/e2e/head.test.ts, examples/e2e/pages-router/src/pages/amp/index.tsx, examples/e2e/pages-router/src/pages/head/index.tsx
sync @opennextjs/aws#845
Note: the AMP test is disabled because it fails - the root cause seems to be `Error: [unenv] https.request
is not implemented yet!`
=> add e2e for next/head and next/amp in pages router

examples/e2e/experimental/e2e/playwright.config.ts, examples/e2e/experimental/e2e/use-cache.test.ts, examples/e2e/experimental/src/app/use-cache/ssr/page.tsx, examples/e2e/experimental/src/components/cached.tsx
Sync with https://github.com/opennextjs/opennextjs-aws/pull/849
=> sync aws #849

.changeset/violet-lemons-think.md, packages/cloudflare/src/cli/commands/populate-cache.ts, packages/cloudflare/src/cli/utils/run-wrangler.ts
`remote` used to be the default but should now be specified explicitly.
=> fix cache population for R2

.changeset/major-comics-divide.md, packages/cloudflare/src/cli/commands/populate-cache.ts
=> fix cache population hanging

examples/e2e/app-pages-router/wrangler.jsonc, examples/e2e/app-router/wrangler.jsonc, examples/e2e/experimental/wrangler.jsonc, examples/e2e/pages-router/wrangler.jsonc, examples/overrides/r2-incremental-cache/wrangler.jsonc, packages/cloudflare/templates/wrangler.jsonc
Wrangler will start enforcing valid bucket names even in dev, see https://github.com/cloudflare/workers-sdk/pull/9165
=> Use valid names for R2 buckets

.changeset/tame-planes-open.md, packages/cloudflare/package.json, packages/cloudflare/src/api/config.ts, packages/cloudflare/src/cli/build/utils/ensure-cf-config.ts, packages/cloudflare/src/cli/templates/init.ts, packages/cloudflare/src/cli/templates/worker.ts, pnpm-lock.yaml
This is just a proposal for now, but this is the best way that i can think of to really reduce cold start for ISR/SSG (in combination with `enableCacheInterception`)
By using that we can go from 600-800ms of cpu time for ISR/SSG during cold start to around 30-40ms. Tested with the app-router e2e app with `enableCacheInterception` and cache purge as well.
This has the drawback of increasing the size of the app.
We should also think if we want to move back the main handler import at the top as well. This could reduce cpu time for SSR route themselves, but could cause issue with thing that are loaded right away like instrumentation (especially if there is I/O)
=> Revert to external middleware

.changeset/olive-lemons-dance.md, .github/actions/setup-playwright/action.yml, .github/workflows/playwright.yml, examples/common/config-e2e.ts, packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts, packages/cloudflare/src/cli/build/patches/plugins/wrangler-external.ts, packages/cloudflare/src/cli/commands/populate-cache.ts
**Changes:**
- Caches playwright browsers.
- Fixes several path normalisation issues.
=> fix a few windows path issues

.changeset/major-mails-shave.md, examples/e2e/experimental/e2e/use-cache.test.ts, examples/e2e/experimental/src/app/use-cache/fetch/page.tsx, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts, packages/cloudflare/src/cli/build/patches/plugins/use-cache.spec.ts, packages/cloudflare/src/cli/build/patches/plugins/use-cache.ts
Using fetch (or I/O in general) inside of a `use cache` in an ISR/SSG route would make it crash with a `Cannot perform I/O on behalf of a different request` error during revalidation request if the instance is warm.
This is because by default it will use `AsyncLocalStorage.snapshot()` and it will bind everything to the initial request context. The downsides is that `use cache` function will have access to the full request ALS context from next (i.e. cookies, headers ...)
=> Fix fetch inside `use cache` in ISR

.changeset/tired-impalas-cover.md, packages/cloudflare/package.json, pnpm-lock.yaml
=> Bump aws version

.changeset/fresh-crews-move.md, packages/cloudflare/src/api/config.ts, packages/cloudflare/src/cli/build/utils/ensure-cf-config.ts
In some cases it's interesting to override some of the default provided by cloudflare.
This add an option in `open-next.config.ts` to only add a warning in case of incorrect validation instead of throwing an error
=> Feat: Disable config validation

.changeset/hip-bags-argue.md, packages/cloudflare/src/cli/templates/init.ts
Closes #686. 
**Important** to note this didn't only affect `next-auth`. All redirects from server actions was affected in preview mode. `wrangler dev` would hang and give an error as it would try to send a request to `https`. 
Through my research I figured out that Next internally uses `process.env.__NEXT_PRIVATE_ORIGIN` in standalone mode. They set it during `startServer` on this [line](https://github.com/vercel/next.js/blob/6b1e48080e896e0d44a05fe009cb79d2d3f91774/packages/next/src/server/lib/start-server.ts#L275). To align with this behavior in preview mode this should be set to the origin during the initialization. 
Affected lines in Next:
- https://github.com/vercel/next.js/blob/6b1e48080e896e0d44a05fe009cb79d2d3f91774/packages/next/src/server/app-render/action-handler.ts#L177-L184 …
=> fix(preview): Ensure the protocol is correct in redirects from server actions during preview mode

.changeset/four-wombats-serve.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/templates/shims/throw.ts
The toolbox optimizer pulls severals MB of dependencies (`caniuse-lite`, `terser`, `acorn`, ...)
Droppping it save >3MB code size on the `playground14` example
Before:
After:
=> perf: drop `@ampproject/toolbox-optimizer` to reduce the server bundle size

.changeset/loud-seas-rhyme.md, package.json, packages/cloudflare/package.json, packages/cloudflare/src/cli/build/open-next/createServerBundle.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Integrate https://github.com/opennextjs/opennextjs-aws/pull/891 (supersedes #702).
~TODO: Update the aws version after 891 is released~
=> perf: drop babel to reduce the server bundle size

.changeset/whole-spiders-stay.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/plugins/open-next.ts, packages/cloudflare/src/cli/build/utils/apply-patches.ts
The "require" patch could be mark as optional - It triggered an error when I was playing with minification settings.
Also:
- Drop a debug `console.error`
- Make `patchCodeWithValidations` less verbose as it is now less used.
=> Make the require patch optional

.changeset/giant-books-dream.md, packages/cloudflare/src/cli/build/bundle-server.ts
Turns on minifying by default as bundle size could have an impact on performance.
This PR stays on the safe side by only minifying whitespaces and syntax. Identifier are explicitly not renamed to avoid runtime issues.
Some result experimenting with a sample app.
The original code size was 7.7MB before bundling.
Before this PR, the output would be 10.2MB
Using the most agressive minification (`minify: true`) -> 6.7MB
Using the safe minification implemented in this PR -> 7.4MB
That a close to 30% improvement.
=> perf: minify the generated bundle by default

examples/playground14/e2e/cloudflare.spec.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Root cause is fixed at https://github.com/cloudflare/workers-sdk/pull/9935
This PR should not be merged until the fix is released to miniflare
=> fix _next/image test

.changeset/modern-buses-think.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/plugins/instrumentation.spec.ts, packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts, packages/cloudflare/src/cli/build/patches/plugins/load-manifest.ts
For #667, #794 and #792.
[This](https://github.com/vercel/next.js/blob/f1b88b4cfa63a6560a04baa209c09065c419969c/packages/next/src/server/lib/router-utils/instrumentation-globals.external.ts#L12-L43) code in Next needs to be patched, and also `loadManifest` also needs to be patched. It will get a path for `required-server-files.json` and `.next/BUILD_ID`.
Tested on `next@15.4.2-canary.1`
Update: This will make instrumenation and loadManifest work on `>=15.4.2`, but there is more patches that need update. Incremental Cache is not getting applied and possibly more issues. Needs more investigation.
=> fix(patches): Update patchInstrumentation and loadManifest to work with Next 15.4

.changeset/empty-garlics-lead.md, packages/cloudflare/src/api/overrides/tag-cache/d1-next-tag-cache.spec.ts, packages/cloudflare/src/api/overrides/tag-cache/d1-next-tag-cache.ts
Closes [803](https://github.com/opennextjs/opennextjs-cloudflare/issues/803)
I also noticed that `D1NextModeTagCache` was missing a unit test, so I had Copilot draft one up. If you don't want that included, let me know and I'll drop that commit.
=> Fix missing SQL parameter bindings in `D1NextModeTagCache.getLastRevalidated()`

packages/cloudflare/src/cli/build/build.ts
See #667 
We'll remove that when 15.4 is supported for now it will avoid having to closing too many issues as duplicates
=> Error when Next >= 15.4

.changeset/great-carrots-hammer.md, packages/cloudflare/src/api/durable-objects/sharded-tag-cache.ts, packages/cloudflare/src/api/overrides/tag-cache/do-sharded-tag-cache.spec.ts, packages/cloudflare/src/api/overrides/tag-cache/do-sharded-tag-cache.ts
Fix regional cache for the DOShardedTagCache.
I open it as a draft PR for now.
Fix #819 
This implementation will store every single tag in their own cache entry.
~~I think we should add an option to the tag cache.~~
~~It may make sense for some cases to store all the tag from `hasBeenRevalidated` in the same cache entry. It could be faster, but will likely ends up with less cache hit.~~
After some thought, i don't think it's worth it, the only times where it could be useful would be if you don't use (or barely) the data cache, and that you have very few ISR/SSG cache entry. Maybe an improvement to do in another PR.
=> Fix regional cache for the DOShardedTagCache

.changeset/loud-mice-know.md, examples/e2e/app-router/open-next.config.ts, packages/cloudflare/src/api/overrides/tag-cache/do-sharded-tag-cache.spec.ts, packages/cloudflare/src/api/overrides/tag-cache/do-sharded-tag-cache.ts
Introduce a configuration option to allow persisting missing tags in the regional tag cache.
This could help reduce the load for the tag cache, but should only be used when the regional cache is properly purged on tag write.
=> Add option to persist missing tags in regional cache

.changeset/seven-bats-push.md, packages/cloudflare/src/cli/build/build.ts, packages/cloudflare/src/cli/build/bundle-server.ts
`pnpm opennextjs-cloudflare build --noMinify` will stop minifying the bundle.
It helps with debugging
/cc @sommeeeer
=> fix: --noMinify stop minifying the bundle

examples/e2e/app-router/app/config-redirect/dest/page.tsx, examples/e2e/app-router/app/config-redirect/page.tsx, examples/e2e/app-router/e2e/config.redirect.test.ts, examples/e2e/app-router/e2e/middleware.redirect.test.ts, examples/e2e/app-router/e2e/middleware.rewrite.test.ts, examples/e2e/app-router/middleware.ts, examples/e2e/app-router/next.config.ts
We need to wait for latest AWS for this one.
Synced with these PRs:
- https://github.com/opennextjs/opennextjs-aws/pull/945
- https://github.com/opennextjs/opennextjs-aws/pull/941
=> chore: Sync e2e with AWS

.changeset/neat-jars-listen.md, packages/cloudflare/src/cli/build/bundle-server.ts, packages/cloudflare/src/cli/build/patches/plugins/node-environment.spec.ts, packages/cloudflare/src/cli/build/patches/plugins/node-environment.ts
The [former patch of next server is not enough](https://github.com/opennextjs/opennextjs-aws/blob/e1048ac9bfffa79d32b1cab810619c41a66187c3/packages/open-next/src/build/patch/patches/patchNextServer.ts#L94).
The code was changed sometimes in Next 15.
We should upstream that to aws.
Before (e2e/experimental)
After
/cc @conico974 @sommeeeer
=> perf: drop the babel dependency

.changeset/six-days-watch.md, packages/cloudflare/src/cli/build/build.ts
Sync of https://github.com/opennextjs/opennextjs-aws/pull/953
Thanks to @szcharlesji for the fix
=> Clean output directory before build to prevent recursive bundling

.changeset/tricky-monkeys-wear.md, examples/e2e/app-router/open-next.config.ts, packages/cloudflare/src/api/overrides/cache-purge/index.ts, packages/cloudflare/src/api/overrides/incremental-cache/regional-cache.ts
relates to https://github.com/opennextjs/opennextjs-cloudflare/issues/879
Before this PR purge cache was detected by looking for the related DO but
- There could be a DO without cache purge being enabled (i.e. no override configured)
- Purge could be enabled in direct mode with no DO
=> fix: detection of cache purge

packages/cloudflare/src/api/overrides/tag-cache/do-sharded-tag-cache.ts
Minor refactor:
- `getConfig` doesn't need to be async
- move the public API towards the top of the file
=> refactor ShardedDOTagCache

packages/cloudflare/src/api/overrides/tag-cache/kv-next-tag-cache.ts
Before this PR, calling `hasBeenRevalidated` would log:
```
(log) [KVNextModeTagCache]  getLastRevalidated tags=_N_T_/layout,_N_T_/[locale]/layout,_N_T_/[locale]/(default)/layout,_N_T_/[locale]/(default)/page,_N_T_/ -> time=0
(log) [KVNextModeTagCache]  hasBeenRevalidated tags=_N_T_/layout,_N_T_/[locale]/layout,_N_T_/[locale]/(default)/layout,_N_T_/[locale]/(default)/page,_N_T_/ lastModified=1759315066989 -> false
```
now it only logs
```  
(log) [KVNextModeTagCache]  hasBeenRevalidated tags=_N_T_/layout,_N_T_/[locale]/layout,_N_T_/[locale]/(default)/layout,_N_T_/[locale]/(default)/page,_N_T_/ lastModified=1759315066989 -> false
```
as `hasBeenRevalidated` (and  `getLastRevalidated`) now calls `#getLastRevalidated` which does not log.
=> refactor: make kv tag cache logs more correct / less verbose
